version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./app:/app
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=MelinaRestoran
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=19111993
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
