version: '3.8'

services:
  app:
    image: milanarestoran-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/MelinaRestoran
    depends_on:
      - postgres
      - redis
    networks:
      - milanarestoran-network
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MelinaRestoran
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19111993
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - milanarestoran-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - milanarestoran-network
    restart: always

networks:
  milanarestoran-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
