-- -- Пример SQL скрипта для вставки 50 блюд
INSERT INTO dish (name, description, price, category_id) VALUES
                                                             ('Steak', 'Juicy grilled steak served with mashed potatoes and vegetables.', 25.0, 1),
                                                             ('Pasta Carbonara', 'Creamy pasta with pancetta, eggs, and Parmesan cheese.', 15.0, 2),
                                                             ('Chicken Alfredo', 'Creamy Alfredo sauce over grilled chicken and fettuccine pasta.', 18.0, 2),
                                                             ('Caesar Salad', 'Fresh romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.', 10.0, 3),
                                                             ('Margherita Pizza', 'Classic Italian pizza topped with tomato sauce, mozzarella, and basil.', 12.0, 4),
                                                             ('Cheeseburger', 'Juicy beef patty with cheddar cheese, lettuce, tomato, and pickles.', 8.0, 5),
                                                             ('Fish and Chips', 'Crispy battered fish served with French fries and tartar sauce.', 14.0, 6),
                                                             ('Sushi Platter', 'Assortment of fresh sushi rolls with soy sauce and wasabi.', 20.0, 7),
                                                             ('Pad Thai', 'Stir-fried rice noodles with shrimp, tofu, peanuts, and vegetables.', 16.0, 8),
                                                             ('Lasagna', 'Layers of pasta with meat sauce, ricotta cheese, and mozzarella.', 18.0, 9),
                                                             ('Pho', 'Vietnamese noodle soup with beef or chicken, fresh herbs, and bean sprouts.', 15.0, 10),
                                                             ('Tacos', 'Soft corn tortillas with seasoned meat, salsa, cilantro, and lime.', 10.0, 11),
                                                             ('Chicken Tikka Masala', 'Grilled chicken in creamy tomato curry sauce with rice.', 17.0, 12),
                                                             ('Shrimp Scampi', 'Sauteed shrimp in garlic butter sauce served over pasta.', 20.0, 13),
                                                             ('Beef Stir Fry', 'Tender beef strips stir-fried with vegetables in a savory sauce.', 16.0, 14),
                                                             ('Greek Salad', 'Mixed greens with tomatoes, cucumbers, olives, feta cheese, and vinaigrette.', 12.0, 3),
                                                             ('BBQ Ribs', 'Slow-cooked pork ribs glazed with barbecue sauce, served with coleslaw.', 22.0, 5),
                                                             ('Vegetarian Pizza', 'Pizza topped with marinara sauce, mozzarella, and assorted vegetables.', 14.0, 4),
                                                             ('Cesar Salad', 'Fresh romaine lettuce with Cesar dressing, croutons, and Parmesan cheese.', 15.0, 6),
                                                             ('Fruit Platter', 'Assortment of fresh fruits including strawberries, kiwi, pineapple, and melon.', 18.0, 7),
                                                             ('Chicken Curry', 'Chicken cooked in a flavorful curry sauce with rice and naan bread.', 19.0, 8),
                                                             ('Mushroom Risotto', 'Creamy risotto rice with mushrooms, Parmesan cheese, and herbs.', 16.0, 9),
                                                             ('Beef Burger', 'Juicy beef patty with lettuce, tomato, onion, pickles, and cheese.', 11.0, 10),
                                                             ('Sushi Rolls', 'Assortment of sushi rolls including California, tuna, and salmon rolls.', 21.0, 11),
                                                             ('Spaghetti Bolognese', 'Spaghetti pasta with hearty meat sauce and Parmesan cheese.', 17.0, 12),
                                                             ('Grilled Salmon', 'Grilled salmon fillet served with steamed vegetables and lemon.', 23.0, 13),
                                                             ('Vegetable Stir Fry', 'Assorted vegetables stir-fried in soy sauce and served over rice noodles.', 13.0, 14),
                                                             ('Caprese Salad', 'Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.', 10.0, 3),
                                                             ('Pulled Pork Sandwich', 'Slow-cooked pulled pork with barbecue sauce on a toasted bun.', 12.0, 5),
                                                             ('Seafood Paella', 'Spanish rice dish with shrimp, mussels, clams, and chorizo.', 25.0, 6),
                                                             ('Falafel Wrap', 'Falafel balls wrapped in pita bread with hummus, lettuce, and tahini sauce.', 14.0, 7),
                                                             ('Beef Pho', 'Vietnamese noodle soup with beef, fresh herbs, bean sprouts, and lime.', 18.0, 8),
                                                             ('Beef Tacos', 'Soft corn tortillas with seasoned beef, salsa, cheese, and cilantro.', 11.0, 9),
                                                             ('Chicken Shawarma', 'Grilled chicken wrapped in pita bread with garlic sauce and veggies.', 13.0, 10),
                                                             ('Vegetarian Sushi', 'Sushi rolls with avocado, cucumber, and carrots, served with soy sauce.', 16.0, 11),
                                                             ('Pesto Pasta', 'Pasta with basil pesto sauce, cherry tomatoes, and Parmesan cheese.', 15.0, 12),
                                                             ('Teriyaki Chicken', 'Grilled chicken marinated in teriyaki sauce, served with rice and vegetables.', 19.0, 13),
                                                             ('Eggplant Parmesan', 'Breaded and baked eggplant slices topped with marinara sauce and mozzarella.', 17.0, 14),
                                                             ('Cobb Salad', 'Mixed greens with grilled chicken, avocado, bacon, eggs, tomatoes, and blue cheese.', 20.0, 3),
                                                             ('BBQ Chicken Pizza', 'Pizza topped with barbecue sauce, grilled chicken, red onions, and cilantro.', 18.0, 4),
                                                             ('Gyro Plate', 'Grilled gyro meat with pita bread, tzatziki sauce, lettuce, tomatoes, and onions.', 16.0, 5),
                                                             ('Vegetable Curry', 'Assorted vegetables cooked in a flavorful curry sauce with rice.', 14.0, 6),
                                                             ('Fettuccine Alfredo', 'Fettuccine pasta in creamy Alfredo sauce with Parmesan cheese.', 15.0, 7),
                                                             ('Shrimp Tempura', 'Lightly battered and fried shrimp served with tempura sauce and rice.', 22.0, 8),
                                                             ('Chicken Enchiladas', 'Corn tortillas filled with shredded chicken, cheese, and enchilada sauce.', 12.0, 9),
                                                             ('Beef Wellington', 'Tender beef filet wrapped in puff pastry with mushroom duxelles and prosciutto.', 30.0, 10);




INSERT INTO dish (name, description, price, category_id) VALUES
                                                             ('Ramen', 'Japanese noodle soup with pork, soft-boiled egg, and assorted toppings.', 14.0, 1),
                                                             ('Beef Stroganoff', 'Tender beef in a creamy mushroom sauce served over egg noodles.', 18.0, 2),
                                                             ('Chicken Parmesan', 'Breaded chicken breast topped with marinara sauce and mozzarella cheese, served with pasta.', 20.0, 3),
                                                             ('Tuna Poke Bowl', 'Diced raw tuna mixed with onions, avocado, and poke sauce, served over rice.', 16.0, 4),
                                                             ('Beef Brisket Sandwich', 'Slow-cooked beef brisket on a brioche bun with coleslaw and barbecue sauce.', 12.0, 5),
                                                             ('Lobster Bisque', 'Creamy soup made with lobster meat and sherry.', 8.0, 6),
                                                             ('Sashimi Platter', 'Assortment of fresh raw fish slices, including tuna, salmon, and yellowtail.', 25.0, 7),
                                                             ('Pad See Ew', 'Stir-fried rice noodles with Chinese broccoli, egg, and soy sauce.', 13.0, 8),
                                                             ('Lasagna Rolls', 'Lasagna noodles rolled with ricotta cheese, spinach, and meat sauce.', 16.0, 9),
                                                             ('Chicken Mole', 'Chicken in a rich, chocolate-chili sauce, served with rice and beans.', 19.0, 10),
                                                             ('Beef Bulgogi', 'Korean-style marinated and grilled beef, served with rice and kimchi.', 17.0, 11),
                                                             ('Vegetable Sushi Roll', 'Sushi roll filled with cucumber, avocado, and carrots.', 10.0, 12),
                                                             ('Shrimp Scampi Linguine', 'Linguine pasta with sautéed shrimp in a garlic butter sauce.', 22.0, 13),
                                                             ('Beef Bourguignon', 'Braised beef in a red wine sauce with mushrooms and pearl onions, served over mashed potatoes.', 24.0, 14),
                                                             ('Quinoa Salad', 'Quinoa mixed with cucumber, tomatoes, feta cheese, and a lemon vinaigrette.', 11.0, 1),
                                                             ('Chicken Tikka Masala Pizza', 'Pizza with grilled chicken, tikka masala sauce, and mozzarella cheese.', 18.0, 2),
                                                             ('Beef Empanadas', 'Flaky pastry filled with seasoned ground beef.', 9.0, 3),
                                                             ('Miso Ramen', 'Japanese noodle soup with miso broth, pork, soft-boiled egg, and assorted toppings.', 15.0, 4),
                                                             ('Chicken Cordon Bleu', 'Breaded chicken breast stuffed with ham and Swiss cheese, served with a creamy sauce.', 21.0, 5),
                                                             ('Seafood Linguine', 'Linguine pasta with shrimp, scallops, and mussels in a white wine sauce.', 23.0, 6),
                                                             ('Beef Tenderloin Steak', 'Grilled beef tenderloin steak served with roasted potatoes and asparagus.', 35.0, 7),
                                                             ('Chicken Satay', 'Grilled chicken skewers served with peanut sauce and cucumber salad.', 14.0, 8),
                                                             ('Vegetable Lasagna', 'Lasagna with layers of vegetables, ricotta cheese, and marinara sauce.', 17.0, 9),
                                                             ('Beef Enchiladas', 'Corn tortillas filled with seasoned ground beef, cheese, and enchilada sauce.', 13.0, 10),
                                                             ('Chicken Fajitas', 'Grilled chicken with sautéed peppers and onions, served with tortillas, guacamole, and salsa.', 16.0, 11),
                                                             ('Sushi Burrito', 'Large sushi roll filled with rice, avocado, cucumber, and your choice of protein.', 12.0, 12),
                                                             ('Beef Stroganoff Baked Potato', 'Baked potato topped with beef stroganoff and sour cream.', 15.0, 13),
                                                             ('Vegetable Fried Rice', 'Fried rice with assorted vegetables, eggs, and soy sauce.', 10.0, 14),
                                                             ('Chicken Caesar Wrap', 'Grilled chicken, romaine lettuce, Parmesan cheese, and Caesar dressing wrapped in a tortilla.', 11.0, 1),
                                                             ('Beef Teriyaki Bowl', 'Grilled beef with teriyaki sauce, served over rice with steamed vegetables.', 18.0, 2),
                                                             ('Shrimp Tempura Roll', 'Sushi roll with shrimp tempura, avocado, and spicy mayo.', 14.0, 3),
                                                             ('Chicken Parmesan Sandwich', 'Breaded chicken breast, marinara sauce, and mozzarella cheese on a brioche bun.', 12.0, 4),
                                                             ('Beef Chili', 'Hearty beef chili served with cornbread and sour cream.', 8.0, 5),
                                                             ('Seafood Bouillabaisse', 'French seafood stew with shrimp, scallops, mussels, and fish in a tomato-saffron broth.', 25.0, 6),
                                                             ('Chicken Tikka Masala Wrap', 'Grilled chicken tikka masala, rice, and cilantro wrapped in a tortilla.', 13.0, 7),
                                                             ('Beef Pho Noodle Soup', 'Vietnamese noodle soup with beef, rice noodles, bean sprouts, and fresh herbs.', 14.0, 8),
                                                             ('Vegetable Pad Thai', 'Stir-fried rice noodles with assorted vegetables, tofu, and peanuts.', 12.0, 9),
                                                             ('Chicken Mole Enchiladas', 'Corn tortillas filled with shredded chicken in mole sauce and cheese.', 16.0, 10),
                                                             ('Beef Bulgogi Lettuce Wraps', 'Korean-style marinated beef with sautéed vegetables, wrapped in lettuce leaves.', 15.0, 11),
                                                             ('Shrimp Tempura Udon', 'Japanese noodle soup with shrimp tempura, udon noodles, and dashi broth.', 18.0, 12),
                                                             ('Beef Bourguignon Pot Pie', 'Beef bourguignon filling baked in a flaky pie crust.', 20.0, 13),
                                                             ('Vegetable Fried Rice Stuffed Tomato', 'Tomato stuffed with vegetable fried rice, served on a bed of greens.', 11.0, 14);



INSERT INTO dish (name, description, price, category_id) VALUES
                                                             ('Beef Tartare', 'Raw chopped beef with capers, onions, and a raw egg yolk.', 22.0, 1),
                                                             ('Lobster Ravioli', 'Pasta stuffed with lobster meat in a creamy tomato sauce.', 25.0, 2),
                                                             ('Chicken Marsala', 'Sautéed chicken in a Marsala wine sauce with mushrooms, served over pasta.', 19.0, 3),
                                                             ('Tuna Poke Nachos', 'Wonton chips topped with raw tuna, avocado, onions, and poke sauce.', 14.0, 4),
                                                             ('Beef Brisket Chili Cheese Fries', 'French fries topped with slow-cooked beef brisket, chili, and cheese.', 12.0, 5),
                                                             ('Lobster Bisque Grilled Cheese', 'Creamy lobster bisque served with a grilled cheese sandwich.', 16.0, 6),
                                                             ('Sashimi Salad', 'Mixed greens with assorted raw fish slices, avocado, and a citrus dressing.', 20.0, 7),
                                                             ('Pad Thai Egg Rolls', 'Crispy egg rolls filled with pad thai ingredients.', 10.0, 8),
                                                             ('Lasagna Stuffed Portobello', 'Baked portobello mushroom cap filled with lasagna ingredients.', 15.0, 9),
                                                             ('Chicken Mole Tostadas', 'Crispy tostadas topped with shredded chicken mole and queso fresco.', 12.0, 10),
                                                             ('Beef Bulgogi Tacos', 'Soft corn tortillas filled with beef bulgogi, kimchi, and gochujang sauce.', 14.0, 11),
                                                             ('Vegetable Sushi Burrito', 'Large sushi roll filled with rice, avocado, cucumber, and assorted vegetables.', 11.0, 12),
                                                             ('Shrimp Scampi Stuffed Mushrooms', 'Baked mushroom caps filled with a shrimp scampi mixture.', 18.0, 13),
                                                             ('Beef Bourguignon Shepherd', 'Beef bourguignon filling topped with mashed potatoes and baked.', 21.0, 14),
('Quinoa Stuffed Avocado', 'Avocado halves filled with quinoa salad, served a bed of greens.', 10.0, 1),
('Chicken Tikka Masala Stuffed Portobello', 'Baked portobello mushroom cap filled with chicken tikka masala.', 17.0, 2),
('Beef Empanada Bites', 'Mini beef empanadas served with a chimichurri dipping sauce.', 8.0, 3),
('Miso Ramen Deviled Eggs', 'Hard-boiled eggs filled with a miso ramen-inspired filling.', 9.0, 4),
('Chicken Cordon Bleu Meatballs', 'Chicken meatballs stuffed with ham and Swiss cheese.', 12.0, 5),
('Seafood Linguine Stuffed Tomato', 'Tomato stuffed with seafood linguine, served on a bed of greens.', 22.0, 6),
('Beef Tenderloin Steak Bites', 'Grilled beef tenderloin steak bites served with a red wine demi-glace.', 28.0, 7),
('Chicken Satay Skewers', 'Grilled chicken satay skewers served with peanut sauce for dipping.', 11.0, 8),
('Vegetable Lasagna Rolls', 'Lasagna noodles rolled with a vegetable ricotta filling.', 16.0, 9),
('Beef Enchilada Stuffed Peppers', 'Bell pepper halves filled with beef enchilada filling and cheese.', 14.0, 10),
('Chicken Fajita Stuffed Avocado', 'Avocado halves filled with grilled chicken fajita mixture.', 13.0, 11),
('Sushi Burrito Bites', 'Mini sushi burrito bites with assorted fillings.', 10.0, 12),
('Beef Stroganoff Stuffed Portobello', 'Baked portobello mushroom cap filled with beef stroganoff.', 18.0, 13),
('Vegetable Fried Rice Stuffed Pepper', 'Bell pepper halves filled with vegetable fried rice.', 11.0, 14),
('Chicken Caesar Salad Bites', 'Romaine lettuce cups filled with chicken Caesar salad.', 9.0, 1),
('Beef Teriyaki Stuffed Mushrooms', 'Baked mushroom caps filled with beef teriyaki mixture.', 15.0, 2),
('Shrimp Tempura Roll Bites', 'Mini shrimp tempura rolls with spicy mayo drizzle.', 12.0, 3),
('Chicken Parmesan Stuffed Tomato', 'Tomato stuffed with breaded chicken parmesan filling.', 11.0, 4),
('Beef Chili Stuffed Potato Skins', 'Potato skins filled with beef chili and cheese.', 10.0, 5),
('Seafood Bouillabaisse Stew Shots', 'Mini servings of seafood bouillabaisse stew.', 18.0, 6),
('Chicken Tikka Masala Stuffed Portobello Bites', 'Mini baked portobello mushroom caps filled with chicken tikka masala.', 14.0, 7),
('Beef Pho Noodle Soup Bites', 'Mini servings of beef pho noodle soup.', 12.0, 8),
('Vegetable Pad Thai Stuffed Avocado', 'Avocado halves filled with vegetable pad thai mixture.', 10.0, 9),
('Chicken Mole Enchilada Bites', 'Mini chicken mole enchiladas.', 13.0, 10),
('Beef Bulgogi Lettuce Wrap Bites', 'Bite-sized beef bulgogi lettuce wraps.', 11.0, 11),
('Shrimp Tempura Udon Soup Shots', 'Mini servings of shrimp tempura udon soup.', 16.0, 12),
('Beef Bourguignon Stuffed Mushroom Caps', 'Baked mushroom caps filled with beef bourguignon mixture.', 17.0, 13),
('Vegetable Fried Rice Stuffed Tomato Bites', 'Mini tomatoes stuffed with vegetable fried rice.', 9.0, 14)